# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='ชื่อธนาคาร')),
                ('account_name', models.CharField(max_length=150, verbose_name='ชื่อบัญชี')),
                ('account_number', models.CharField(max_length=20, verbose_name='เลขที่บัญชี')),
                ('promptpay_id', models.CharField(blank=True, max_length=15, verbose_name='เบอร์ PromptPay / เลขผู้เสียภาษี')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'บัญชีธนาคาร',
                'verbose_name_plural': 'บัญชีธนาคาร',
                'ordering': ['sort_order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('method', models.CharField(choices=[('cash', 'เงินสด'), ('promptpay', 'PromptPay'), ('bank_transfer', 'โอนผ่านธนาคาร'), ('credit_card', 'บัตรเครดิต'), ('cheque', 'เช็ค')], max_length=15, verbose_name='วิธีชำระ')),
                ('reference_number', models.CharField(blank=True, help_text='Slip number for bank transfer / PromptPay', max_length=50, verbose_name='เลขอ้างอิง')),
                ('is_deposit', models.BooleanField(default=False, verbose_name='เป็นมัดจำ')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่รับ')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('bank_account', models.ForeignKey(blank=True, help_text='Required for bank_transfer payments', null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bankaccount', verbose_name='บัญชีที่รับโอน')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='jobs.job', verbose_name='งาน')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='รับเงินโดย')),
            ],
            options={
                'verbose_name': 'การชำระเงิน',
                'verbose_name_plural': 'การชำระเงิน',
                'ordering': ['-received_at'],
            },
        ),
    ]
