# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
import jobs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'อนุมัติ'), ('revision', 'ขอแก้ไข')], max_length=10)),
                ('revision_notes', models.TextField(blank=True, verbose_name='หมายเหตุการแก้ไข')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by_customer', models.BooleanField(default=False, help_text='True if customer approved directly (Phase 2); False if staff recorded')),
            ],
            options={
                'verbose_name': 'การอนุมัติ',
                'verbose_name_plural': 'การอนุมัติ',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jobs.models.job_file_upload_path, verbose_name='ไฟล์')),
                ('file_type', models.CharField(choices=[('artwork', 'ไฟล์งานลูกค้า'), ('proof', 'ไฟล์ proof'), ('reference', 'ไฟล์อ้างอิง'), ('output', 'ไฟล์ผลงาน')], default='artwork', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'ไฟล์งาน',
                'verbose_name_plural': 'ไฟล์งาน',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('designing', 'กำลังออกแบบ'), ('awaiting_approval', 'รอลูกค้าอนุมัติ'), ('revision', 'แก้ไขงาน'), ('approved', 'อนุมัติแล้ว'), ('printing', 'กำลังพิมพ์'), ('cutting', 'กำลังตัด'), ('laminating', 'กำลังเคลือบ'), ('ready', 'พร้อมรับ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('on_hold', 'พักงาน')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('designing', 'กำลังออกแบบ'), ('awaiting_approval', 'รอลูกค้าอนุมัติ'), ('revision', 'แก้ไขงาน'), ('approved', 'อนุมัติแล้ว'), ('printing', 'กำลังพิมพ์'), ('cutting', 'กำลังตัด'), ('laminating', 'กำลังเคลือบ'), ('ready', 'พร้อมรับ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('on_hold', 'พักงาน')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ประวัติสถานะ',
                'verbose_name_plural': 'ประวัติสถานะ',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='กว้าง (ซม.)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='สูง (ซม.)')),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาที่เสนอ')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='มัดจำ')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ส่วนลด')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('designing', 'กำลังออกแบบ'), ('awaiting_approval', 'รอลูกค้าอนุมัติ'), ('revision', 'แก้ไขงาน'), ('approved', 'อนุมัติแล้ว'), ('printing', 'กำลังพิมพ์'), ('cutting', 'กำลังตัด'), ('laminating', 'กำลังเคลือบ'), ('ready', 'พร้อมรับ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('on_hold', 'พักงาน')], db_index=True, default='pending', max_length=20, verbose_name='สถานะ')),
                ('payment_status', models.CharField(choices=[('unpaid', 'ยังไม่ชำระ'), ('partial', 'ชำระบางส่วน'), ('paid', 'ชำระครบ')], default='unpaid', max_length=10, verbose_name='สถานะการชำระ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดส่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_notes', models.TextField(blank=True, verbose_name='หมายเหตุภายใน')),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_jobs', to=settings.AUTH_USER_MODEL, verbose_name='นักออกแบบ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_jobs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับงาน')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'งาน',
                'verbose_name_plural': 'งาน',
                'ordering': ['-created_at'],
            },
        ),
    ]
