# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.producttype', verbose_name='ประเภทสินค้า'),
        ),
        migrations.AddField(
            model_name='jobapproval',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapproval',
            name='proof_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobfile', verbose_name='ไฟล์ proof ที่ส่งให้'),
        ),
        migrations.AddField(
            model_name='jobstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='เปลี่ยนโดย'),
        ),
        migrations.AddField(
            model_name='jobstatushistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'status'], name='jobs_job_custome_522329_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tracking_token'], name='jobs_job_trackin_418f97_idx'),
        ),
    ]
