# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อวัสดุ')),
                ('unit', models.CharField(help_text='e.g. ม้วน, แผ่น, กก.', max_length=20, verbose_name='หน่วย')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ต้นทุน/หน่วย (บาท)')),
                ('quantity_in_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='คงเหลือ')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ขั้นต่ำก่อนแจ้งเตือน')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'วัสดุ',
                'verbose_name_plural': 'วัสดุ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ประเภทสินค้า')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='ชื่อภาษาอังกฤษ')),
                ('unit', models.CharField(default='ชิ้น', help_text='e.g. ชิ้น, ตร.ม., เมตร', max_length=30, verbose_name='หน่วย')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาฐาน')),
                ('pricing_method', models.CharField(choices=[('flat', 'ราคาคงที่'), ('per_sqm', 'ต่อตารางเมตร'), ('per_unit', 'ต่อชิ้น')], default='per_unit', max_length=20, verbose_name='วิธีคิดราคา')),
                ('requires_design', models.BooleanField(default=True, verbose_name='ต้องผ่านขั้นตอนออกแบบ')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ประเภทสินค้า',
                'verbose_name_plural': 'ประเภทสินค้า',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='จำนวนที่ใช้')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='jobs.job', verbose_name='งาน')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.material', verbose_name='วัสดุ')),
            ],
            options={
                'verbose_name': 'การใช้วัสดุ',
                'verbose_name_plural': 'การใช้วัสดุ',
            },
        ),
    ]
