# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='รายการ')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='จำนวน')),
                ('unit', models.CharField(default='ชิ้น', max_length=30, verbose_name='หน่วย')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา/หน่วย')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอด')),
            ],
            options={
                'verbose_name': 'รายการสินค้า',
                'verbose_name_plural': 'รายการสินค้า',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='คีย์')),
                ('value', models.TextField(verbose_name='ค่า')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'ตั้งค่าระบบ',
                'verbose_name_plural': 'ตั้งค่าระบบ',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'ใบเสนอราคา'), ('tax_invoice', 'ใบกำกับภาษี'), ('receipt', 'ใบเสร็จรับเงิน'), ('credit_note', 'ใบลดหนี้')], max_length=20, verbose_name='ประเภทเอกสาร')),
                ('document_number', models.CharField(help_text='ออกอัตโนมัติ เช่น TX-2025-00001', max_length=20, unique=True, verbose_name='เลขที่เอกสาร')),
                ('sequence', models.PositiveIntegerField(verbose_name='ลำดับ')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ปี พ.ศ./ค.ศ.')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ชื่อลูกค้า')),
                ('customer_address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('customer_tax_id', models.CharField(blank=True, max_length=13, verbose_name='เลขผู้เสียภาษี')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดก่อนภาษี')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=7, max_digits=5, verbose_name='อัตรา VAT (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวม')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ออก')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('is_void', models.BooleanField(default=False, verbose_name='ยกเลิก')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ออกโดย')),
            ],
            options={
                'verbose_name': 'เอกสาร',
                'verbose_name_plural': 'เอกสาร',
                'ordering': ['-issued_at'],
            },
        ),
    ]
