# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='jobs.job', verbose_name='งาน'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'year', 'sequence'], name='documents_d_documen_c6c339_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['job'], name='documents_d_job_id_698265_idx'),
        ),
    ]
