# Generated by Django 6.0.2 on 2026-02-26 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ประเภทลูกค้า')),
                ('credit_days', models.PositiveSmallIntegerField(default=0, help_text='0 = ชำระทันที, 30 = Net30', verbose_name='เครดิต (วัน)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ส่วนลด (%)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ประเภทลูกค้า',
                'verbose_name_plural': 'ประเภทลูกค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ / ชื่อบริษัท')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('line_user_id', models.CharField(blank=True, help_text='Phase 2: filled when customer links LINE account', max_length=50, verbose_name='LINE User ID')),
                ('is_corporate', models.BooleanField(default=False, verbose_name='นิติบุคคล')),
                ('tax_id', models.CharField(blank=True, help_text='13 หลัก สำหรับออกใบกำกับภาษี', max_length=13, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('billing_address', models.TextField(blank=True, verbose_name='ที่อยู่สำหรับออกใบกำกับ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customertype', verbose_name='ประเภท')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['tax_id'], name='customers_c_tax_id_c2c068_idx')],
            },
        ),
    ]
